"""Write reports/data_quality.md from the checks' results (make quality, after checks).

Sections: verdict, scorecard per table and per dimension, everything that needs attention
(errors and warnings, with examples), measurements (cutoff ties, missing data), lineage from
bronze to gold, freshness and the update policy, and a few insights computed from gold.
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from pathlib import Path

import duckdb

from bianque.config import Settings, load_settings
from bianque.pipeline.contracts import load_contracts
from bianque.quality.checks import results_path

log = logging.getLogger("bianque.quality")

REPORT = Path("reports/data_quality.md")
DIMENSIONS = (
    "completeness", "uniqueness", "validity", "consistency", "integrity", "lineage", "timeliness",
)  # fmt: skip
TOP_MISSING = 15


def pct(x: float) -> str:
    if x == 0:
        return "0%"
    if x < 0.0001:
        return f"{x:.4%}"
    return f"{x:.2%}" if x < 0.01 else f"{x:.1%}"


def missing_notes(settings: Settings) -> dict[tuple[str, str], str]:
    """Why some columns are mostly NULL by design, so they are not read as negligence."""
    notes = {}
    for c in load_contracts(settings.contracts_dir).values():
        for fk in c.foreign_keys:
            if fk.on_orphan == "nullify":
                notes[(c.table, fk.column)] = "set to NULL by silver: random IDs in the source"
    notes[("complaints", "origin_interaction_id")] = "always NULL in the source"
    return notes


def insights(settings: Settings) -> list[str]:
    """A few numbers from gold that frame the problem Bianque addresses."""
    g = settings.gold_root
    con = duckdb.connect()

    def rel(name: str) -> str:
        return f"read_parquet('{g}/{name}/**/*.parquet', hive_partitioning = true)"

    fraud = con.sql(f"""
        SELECT year(process_date) AS y, count(*) AS n, sum(is_fraud::INT) AS k,
               avg((source_fraud_score IS NULL)::INT) AS unscored
        FROM {rel("transaction_features")} GROUP BY 1 ORDER BY 1""").fetchall()
    disputes = con.sql(f"""
        SELECT count(*), avg(sla_breached::INT), avg(is_regulator::INT),
               median(resolution_days), avg(has_compensation::INT)
        FROM {rel("dispute_outcomes")}""").fetchone()
    service = con.sql(f"""
        SELECT sum(contacts_per_month), sum(cost_per_month_usd)
        FROM {rel("service_cost_baseline")}""").fetchone()
    channels = con.sql(f"""
        SELECT channel, cost_per_delivered, open_rate FROM {rel("channel_costs")}
        ORDER BY cost_per_delivered""").fetchall()
    lines = [
        "| Year | Transactions | Frauds | Fraud rate | Without a fraud score |",
        "|---|---:|---:|---:|---:|",
    ]
    lines += [f"| {y} | {n:,} | {k:,} | {pct(k / n)} | {pct(u)} |" for y, n, k, u in fraud]
    n, sla, reg, days, comp = disputes
    lines += [
        "",
        "- **Fraud is rare and stable**, and one transaction in five has no fraud score, so "
        "nothing can flag it proactively (the reactive path covers it).",
        f"- **Complaints are expensive when they arrive:** {n:,} complaints; {pct(sla)} breach "
        f"their SLA, {pct(reg)} reach the regulator, the median takes {days:.0f} days to "
        f"resolve, and {pct(comp)} end with compensation.",
        f"- **The status quo** handles about {service[0]:,.0f} service contacts a month, about "
        f"USD {service[1]:,.0f} a month (synthetic cost per contact, `cost_assumptions_v1`).",
        "- **Reaching a customer costs cents:** "
        + "; ".join(
            f"{c} USD {cost:.4f} per delivered message"
            + (f" ({pct(rate)} opened)" if rate is not None else " (response not tracked)")
            for c, cost, rate in channels
        )
        + ".",
        "",
        "More in [`docs/silver_data_findings.md`](../docs/silver_data_findings.md) §9 and "
        "[`docs/gold_design.md`](../docs/gold_design.md) §5.",
    ]
    return lines


def render(results: dict, settings: Settings) -> str:
    checks = results["checks"]
    errors = [c for c in checks if c["severity"] == "error"]
    warns = [c for c in checks if c["severity"] == "warn"]
    failed_e = [c for c in errors if not c["passed"]]
    failed_w = [c for c in warns if not c["passed"]]
    verdict = "PASS" if not failed_e else "FAIL"
    lines = [
        "# Data quality report",
        "",
        f"Generated by `make quality` (`src/bianque/quality/`) on {results['run_at']}, in "
        f"{results['seconds']} s. Checks are generated from the contracts in "
        "[`contracts/`](../contracts/) and run on the silver and gold tables of the real data. "
        "Deviations from the data dictionary, and why, are documented in "
        "[`docs/silver_data_findings.md`](../docs/silver_data_findings.md).",
        "",
        f"## Verdict: **{verdict}**",
        "",
        "| Severity | Meaning | Checks | Failed |",
        "|---|---|---:|---:|",
        f"| error | A contract rule is broken | {len(errors)} | **{len(failed_e)}** |",
        f"| warn | Worth a look; does not block | {len(warns)} | {len(failed_w)} |",
        f"| info | Measurement only (missing-data rates, ties) | "
        f"{sum(c['severity'] == 'info' for c in checks)} | - |",
        "",
        "## By dimension",
        "",
        "| Dimension | What is checked | Error checks passed |",
        "|---|---|---:|",
    ]
    meaning = {
        "completeness": "Required values present; amount_usd filled",
        "uniqueness": "One row per primary key",
        "validity": "Allowed values (per element in list columns) and ranges",
        "consistency": "Structural NULLs; the business-day rule of process_date; business rules",
        "integrity": "Foreign keys resolve in their parent table",
        "lineage": "Bronze rows = silver + quarantine + duplicates removed; gold matches silver",
        "timeliness": "Freshness of each fact table; process days without data",
    }
    for d in DIMENSIONS:
        es = [c for c in errors if c["dimension"] == d]
        lines.append(
            f"| {d} | {meaning[d]} | {sum(c['passed'] for c in es)} / {len(es)} |"
            if es
            else f"| {d} | {meaning[d]} | warnings only |"
        )
    by_table = defaultdict(list)
    for c in checks:
        by_table[c["table"]].append(c)
    lines += [
        "",
        "## By table",
        "",
        "| Table | Rows | Error checks passed | Warnings |",
        "|---|---:|---:|---:|",
    ]
    for table, cs in sorted(by_table.items()):
        rows = max((c["total"] for c in cs if c["dimension"] == "uniqueness"), default=None)
        es = [c for c in cs if c["severity"] == "error"]
        ws = [c for c in cs if c["severity"] == "warn" and not c["passed"]]
        lines.append(
            f"| {table} | {f'{rows:,}' if rows is not None else '-'} "
            f"| {sum(c['passed'] for c in es)} / {len(es)} | {len(ws)} |"
        )
    lines += ["", "## Needs attention", ""]
    attention = failed_e + failed_w
    if not attention:
        lines.append("Nothing: every error and warning check passed.")
    else:
        lines += ["| Severity | Table | Check | Column | Failing | Rate | Detail / examples |",
                  "|---|---|---|---|---:|---:|---|"]  # fmt: skip
        for c in attention:
            extra = c["detail"] or ", ".join(c["examples"])
            lines.append(
                f"| {c['severity']} | {c['table']} | {c['name']} | {c['column'] or '-'} "
                f"| {c['failing']:,} / {c['total']:,} | {pct(c['rate'])} | {extra} |"
            )
    ties = [c for c in checks if c["name"].startswith("events at exactly") and c["failing"]]
    lines += [
        "",
        "## Measurements",
        "",
        "### Events at exactly the business-day cutoff",
        "",
        "`process_date` is the source's business day: events before a cutoff hour belong to the",
        "previous day. At exactly the cutoff second the source assigns either day, about half",
        "each, consistent with timestamps truncated to the second. The check accepts either day",
        "there and counts those rows apart instead of hiding them.",
        "",
        "| Table | Rows at the cutoff second | Of all rows |",
        "|---|---:|---:|",
    ]
    lines += [f"| {c['table']} | {c['failing']:,} | {pct(c['rate'])} |" for c in ties]
    missing = sorted(
        (c for c in checks if c["name"].startswith("missing") and c["failing"]),
        key=lambda c: -c["rate"],
    )
    lines += [
        "",
        f"### Missing data (top {TOP_MISSING} of {len(missing)} columns with NULLs)",
        "",
        "Rates exclude structural NULLs (rows where the field does not apply). Missing values",
        "are reported, never filled.",
        "",
        "| Table | Column | Missing | Of rows where it applies | Note |",
        "|---|---|---:|---:|---|",
    ]
    notes = missing_notes(settings)
    lines += [
        f"| {c['table']} | {c['column']} | {c['failing']:,} | {pct(c['rate'])} "
        f"| {notes.get((c['table'], c['column']), 'missing data')} |"
        for c in missing[:TOP_MISSING]
    ]
    lineage = [c for c in checks if c["dimension"] == "lineage" and c["detail"]]
    lines += [
        "",
        "## Lineage: bronze to gold",
        "",
        "Every row has `_source_key`, `_source_etag` and `_ingested_at` back to its S3 object.",
        "",
        "| Table | Check | Result | Counts |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {c['table']} | {c['name']} | {'pass' if c['passed'] else '**fail**'} | {c['detail']} |"
        for c in lineage
    ]
    fresh = [c for c in checks if c["dimension"] == "timeliness"]
    policy = results["update_policy"]
    lines += [
        "",
        "## Freshness and update policy",
        "",
        "| Table | Check | Result | Detail |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {c['table']} | {c['name']} | {'pass' if c['passed'] else '**warn**'} "
        f"({c['failing']:,}) | {c['detail']} |"
        for c in fresh
    ]
    watermarks = sorted({s["watermark"] for s in policy["silver_watermarks"].values()})
    lines += [
        "",
        "| Layer | Update policy | State now |",
        "|---|---|---|",
        f"| Bronze | Incremental by S3 key and ETag; a changed object overwrites its own file | "
        f"Last ingestion {policy['last_bronze_ingestion']} |",
        f"| Silver | Facts: months touched by new files plus a {policy['late_arrival_days']}-day "
        "trailing window before the watermark; full rebuild when contracts or code change | "
        f"Watermarks {', '.join(watermarks)} |",
        "| Gold | Full rebuild from silver every run; frozen evaluation sets verified by hash | "
        "See `make gold` |",
        "",
        "The data is a static extract, so update correctness is shown with the team-generated "
        "late-arrival fixture ([`fixtures/README.md`](../fixtures/README.md), "
        "`tests/test_late_arrival.py`).",
        "",
        "## Insights",
        "",
        *insights(settings),
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    settings = load_settings()
    results = json.loads(results_path(settings).read_text())
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(render(results, settings))
    log.info("wrote %s", REPORT)


if __name__ == "__main__":
    main()
